version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
    versioning-strategy: increase
