name: CI SDK PHP

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * *" # Everyday at 2:00AM
  workflow_dispatch:
    inputs:
      reason:
        description: "Trigger Comment (Optional)"
        required: false
        default: "Manual Workflow Run"


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACROLINX_ACCESS_TOKEN: ${{ secrets.ACROLINX_ACCESS_TOKEN }}
      ACROLINX_TEST_SERVER_URL: ${{ secrets.ACROLINX_TEST_SERVER_URL }}
      ACROLINX_SSO_USER: ${{ secrets.ACROLINX_SSO_USER }}
      ACROLINX_SSO_PASSWORD: ${{ secrets.ACROLINX_SSO_PASSWORD }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE }}

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - run: composer install
      - run: composer update
      - run: composer test

